### PR TITLE
OT-678: Logout

### LINKED ISSUE #294: Logout
**Is your feature request related to a problem? Please describe.**
It's currently not possible to logout of the app.

**Describe the solution you'd like**
A logout should be possible from within the settings.

[Internal bug tracker](https://jira.open-xchange.com/browse/OT-424)

### PR DESCRIPTION
**Pull request by ghost**
### Link to the given issue
Fixes [#294](https://github.com/open-xchange/ox-coi/issues/294).

### Changes
* Adds *Logout* button in user profile
* Adds logout confirmation alert
* Adds native part in Swift (application and plugin) to handle dropping DCC database and termination of the app

### CODE REVIEW

**Comment by florianhaar** [comment]
The Android team has to add the new method: static const String methodLogout = "context_logout";

**Comment by ghost** [comment]
> The Android team has to add the new method: static const String methodLogout = "context_logout";

@florianhaar And the native part on your side of course to perform a logout/restart.

**Review by florianhaar — COMMENTED** [review]
Looks good.

**Review by florianhaar — APPROVED** [review]

**Review by Boehrsi — CHANGES_REQUESTED** [review]
Some questions / ideas from my side:

- Is there a specific reason for deleting the database in the native parts and not in the Dart part? If not let's move it to the Dart part
- The logout handling shouldn't be related to the "context classes" we have in the native code. Those classes / files are mostly related to the DCC API and we should try to avoid mixing stuff here. Our own stuff should go somewhere else, e.g. the base classes we use

**Comment by ghost** [comment]
> * Is there a specific reason for deleting the database in the native parts and not in the Dart part? If not let's move it to the Dart part

Hm. Good point. I was not aware of that is possible from Dart side. Will have a look.

> * The logout handling shouldn't be related to the "context classes" we have in the native code. Those classes / files are mostly related to the DCC API and we should try to avoid mixing stuff here. Our own stuff should go somewhere else, e.g. the base classes we use

True.

**Comment by florianhaar** [comment]
Added Android changes.

**Review by Boehrsi — APPROVED** [review]

**Comment by Boehrsi** [comment]
Fixed by https://github.com/open-xchange/flutter-deltachat-core/commit/838934cfdef13f888afa037fba05809d1062a373

**Pull request closed without merging**
